### ISSUE TITLE
Older versions of vrepPlusPlus an vrepStubsGen no longer available

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [CoppeliaRobotics/libPlugin#1]
I understand that there has been some wide spread name changing from vrep to sim across most repos. However we were building an old version of the simOMPLExt that was depending on the old versions of vrepPlusPlus and vrePstubsGen which are no longer available. Is there some way to find these repos? More specifically the versions from here: https://github.com/CoppeliaRobotics/simExtOMPL/tree/766a49f3cdcbb19eb2a842fd2290a710839d6898/external

**Comment by Coppelia** [comment]
I have made those old repositories public again.
Cheers
