### ISSUE TITLE
Error compiling simRosInterface

### ISSUE THREAD

**Issue by markscalderon** [CoppeliaRobotics/libPlugin#3]
I tried to compile the package simRosInterface, I updated the libPlugin but when it showed this error. How can I solve it?

[ 52%] Generating generated/stubs.cpp, generated/stubs.h, generated/lua_calltips.cpp
"/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/libPlugin/simStubsGen/generate.py" --xml-file /mnt/d/catkin_ws/src/sim_ros_interface/meta/callbacks.xml --lua-file /mnt/d/catkin_ws/src/sim_ros_interface/simExtROSInterface.lua --gen-all /mnt/d/catkin_ws/src/sim_ros_interface/build/generated
python "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/libPlugin/simStubsGen/external/pycpp/pycpp.py" -p xml_file=/mnt/d/catkin_ws/src/sim_ros_interface/meta/callbacks.xml -i "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/libPlugin/simStubsGen/cpp/stubs.cpp" -o /mnt/d/catkin_ws/src/sim_ros_interface/build/generated/stubs.cpp -P "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/libPlugin/simStubsGen"
Traceback (most recent call last):
  File "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/libPlugin/simStubsGen/external/pycpp/pycpp.py", line 200, in <module>
    pycpp = PyCPP(input_str=input_str, params=params)
  File "/mnt/c/Program Files/CoppeliaRobotics/CoppeliaSimEdu/programming/libPlugin/simStubsGen/external/pycpp/pycpp.py", line 101, in __init__
    raise RuntimeError('line {:d}: unexpected "{}" after "{}"'.format(line.no, line.text, cur.tag))
" after "for" line 911: unexpected "else:
failed to run external/pycpp/pycpp
CMakeFiles/simExtROSInterface.dir/build.make:61: recipe for target 'generated/stubs.cpp' failed
make[2]: *** [generated/stubs.cpp] Error 1
CMakeFiles/Makefile2:2531: recipe for target 'CMakeFiles/simExtROSInterface.dir/all' failed
make[1]: *** [CMakeFiles/simExtROSInterface.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fferri** [comment]
I can't reproduce your issue.

Try again with _fresh git clones_.

You need to specify all the steps needed to reproduce your issue. E.g.:

```
cd ~/catkin_ws/src
git clone https://github.com/CoppeliaRobotics/simExtROSInterface sim_ros_interface
cd sim_ros_interface
git clone https://github.com/CoppeliaRobotics/libPlugin
catkin clean
catkin build --cmake-args -DLIBPLUGIN_DIR=$PWD/libPlugin
```

which builds fine on my machine.

**Comment by markscalderon** [comment]
I solved it :D. My steps are:

Install this package before compiling
    sudo apt install xsltproc

To compile the package:

cd [path_catkin_ws]/src
rm -rf sim_ros_interface libPlugin
git clone https://github.com/CoppeliaRobotics/simExtROSInterface sim_ros_interface
cd sim_ros_interface
git clone https://github.com/CoppeliaRobotics/libPlugin
cd ../..
export COPPELIASIM_ROOT_DIR= [path_of_CoppeliaRobotics]/CoppeliaSimEdu
catkin_make --cmake-args -DLIBPLUGIN_DIR=$PWD/src/sim_ros_interface/libPlugin
