### ISSUE TITLE
CoppeliaSim headers are not up to date

### ISSUE THREAD

**Issue by antoniopurificato** [CoppeliaRobotics/libPlugin#7]
I am trying to install Ros interface for Coppeliasim with Python 3.8, but when I get to build my catkin package I get this errors (in photo).
![Screenshot from 2021-04-02 18-26-32](https://user-images.githubusercontent.com/80911741/113435426-0ffc8a00-93e3-11eb-9c78-d659c6b14a18.png)

**Comment by fferri** [comment]
That means you have to update programming/include and programming/common from git.

**Comment by minecraftadj48** [comment]
[git connection refused.](fatal: unable to access 'https://github.com/CoppeliaRobotics/simExtROSInterface.git/': Failed to receive SOCKS4 connect request ack.)
fatal: unable to access 'https://github.com/CoppeliaRobotics/simExtROSInterface.git/': Failed to connect to 127.0.0.1 port 1080: Connection refused

**Comment by minecraftadj48** [comment]
git connection refused in terminal. how can i update them manually using firefox github?
